blank_issues_enabled: false
contact_links:
  - name: "✉️ Contact form / お問い合わせフォーム"
    url: "https://docs.google.com/forms/d/e/1FAIpQLSf0-A1ysrWQFCDuOZY8f2uH5KhUCB5yqi7TlLEsgl95Q9WKtw/viewform"
    about: "If you prefer not to open an issue / Issue以外で連絡したい場合はこちら"
