blank_issues_enabled: false
contact_links:
  - name: "ğŸ“– How to use / ä½¿ã„æ–¹"
    url: "https://lgtmeow.com/docs/how-to-use"
    about: "If youâ€™re unsure, please check the docs first. / è¿·ã£ãŸã‚‰ã¾ãšã¯ã“ã¡ã‚‰ã‚’ã”ç¢ºèªãã ã•ã„ã€‚"
